spring.application.name=sistema-alertme

# URL de conexão
spring.datasource.url=jdbc:postgresql://localhost:5432/DBAlertMe
spring.datasource.username=postgres_user_here
spring.datasource.password=postgres_password_here

# Cria ou atualiza as tabelas automaticamente ao iniciar o projeto
spring.jpa.hibernate.ddl-auto=update

# API do VirusTotal
virustotal.api.key=virustotal_api_key_here
virustotal.api.url=https://www.virustotal.com/api/v3/urls

# Exibe os comandos SQL no console  (para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
