spring.application.name=sistema-alertme

# Porta dinâmica obrigatória para o Render
server.port=${PORT:8080}

# Chave da API Gemini (Injetada via variável de ambiente no Render)
gemini.api.key=${GEMINI_API_KEY}

# Configuração do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/DBAlertMe
spring.datasource.username=postgres_user_here
spring.datasource.password=postgres_password_here

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API do VirusTotal
virustotal.api.key=api_key_here
virustotal.api.url=https://www.virustotal.com/api/v3/urls

# Logs e Debug de comandos SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true